language: go 

install:
        - go get github.com/mitchellh/gox
        - go build github.com/mitchellh/gox

script: 
        - $HOME/gopath/bin/gox -build-toolchain -osarch="linux/amd64 linux/386 darwindows/386 darwindows/amd64 windows/386 windows/amd64"
        - $HOME/gopath/bin/gox -osarch="linux/amd64 linux/386 darwindows/386 darwindows/amd64 windows/386 windows/amd64"

deploy:
  provider: releases
  api_key:
    secure: Hx8BYRzoUTL724uMiyZ4uEv229x8olxRzMl/ZCNVpseslcWFRROWaZ47nC9oHKMMWdSQitpJRzj1SC5f4pAb+WhaPxtjN04DOyM9dOokb0m2VXjNb1jA/as3JuaTXZgAW5GAb/wD9eKVILHRsQbjieY5EDl6d4HK1iH//BJej5E=
  file: "cigotest_linux_amd64"
          #- ".cigotest_linux_386"
          # - "cigotest_linux_amd64"
          #- ".cigotest_darwindows_386"
          #- ".cigotest_darwindows_amd64"
          #- ".cigotest_windows_386"
          #- ".cigotest_windows_amd64"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: capitancambio/cigotest
